// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Harrison314.PassiveMQ.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CountMessageDto
    {
        /// <summary>
        /// Initializes a new instance of the CountMessageDto class.
        /// </summary>
        public CountMessageDto() { }

        /// <summary>
        /// Initializes a new instance of the CountMessageDto class.
        /// </summary>
        public CountMessageDto(Guid? queuId = default(Guid?), int? count = default(int?))
        {
            QueuId = queuId;
            Count = count;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "queuId")]
        public Guid? QueuId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

    }
}
