// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Harrison314.PassiveMQ.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ErrorResponseDto
    {
        /// <summary>
        /// Initializes a new instance of the ErrorResponseDto class.
        /// </summary>
        public ErrorResponseDto() { }

        /// <summary>
        /// Initializes a new instance of the ErrorResponseDto class.
        /// </summary>
        public ErrorResponseDto(string exceptionName = default(string), IList<string> messages = default(IList<string>), string developerMeesage = default(string))
        {
            ExceptionName = exceptionName;
            Messages = messages;
            DeveloperMeesage = developerMeesage;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exceptionName")]
        public string ExceptionName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "messages")]
        public IList<string> Messages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "developerMeesage")]
        public string DeveloperMeesage { get; set; }

    }
}
