// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Harrison314.PassiveMQ.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MessagePublishDtoMessage : MessageCrateReqDto
    {
        /// <summary>
        /// Initializes a new instance of the MessagePublishDtoMessage class.
        /// </summary>
        public MessagePublishDtoMessage() { }

        /// <summary>
        /// Initializes a new instance of the MessagePublishDtoMessage class.
        /// </summary>
        public MessagePublishDtoMessage(string content, string label = default(string))
            : base(content, label)
        {
        }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
