// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Harrison314.PassiveMQ.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MessageDto
    {
        /// <summary>
        /// Initializes a new instance of the MessageDto class.
        /// </summary>
        public MessageDto() { }

        /// <summary>
        /// Initializes a new instance of the MessageDto class.
        /// </summary>
        public MessageDto(Guid? id = default(Guid?), DateTime? insertionTime = default(DateTime?), DateTime? nextVisibleTime = default(DateTime?), string label = default(string), string content = default(string), int? retryCount = default(int?))
        {
            Id = id;
            InsertionTime = insertionTime;
            NextVisibleTime = nextVisibleTime;
            Label = label;
            Content = content;
            RetryCount = retryCount;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "insertionTime")]
        public DateTime? InsertionTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nextVisibleTime")]
        public DateTime? NextVisibleTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "content")]
        public string Content { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "retryCount")]
        public int? RetryCount { get; set; }

    }
}
