// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Harrison314.PassiveMQ.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MessagePublishDto
    {
        /// <summary>
        /// Initializes a new instance of the MessagePublishDto class.
        /// </summary>
        public MessagePublishDto() { }

        /// <summary>
        /// Initializes a new instance of the MessagePublishDto class.
        /// </summary>
        public MessagePublishDto(string topic, MessagePublishDtoMessage message)
        {
            Topic = topic;
            Message = message;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "topic")]
        public string Topic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public MessagePublishDtoMessage Message { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Topic == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Topic");
            }
            if (Message == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Message");
            }
            if (this.Topic != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(this.Topic, "(/[A-Za-z0-9_]+)+"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "Topic", "(/[A-Za-z0-9_]+)+");
                }
            }
            if (this.Message != null)
            {
                this.Message.Validate();
            }
        }
    }
}
