// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Harrison314.PassiveMQ.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class NotificationAdressUpdateDto
    {
        /// <summary>
        /// Initializes a new instance of the NotificationAdressUpdateDto
        /// class.
        /// </summary>
        public NotificationAdressUpdateDto() { }

        /// <summary>
        /// Initializes a new instance of the NotificationAdressUpdateDto
        /// class.
        /// </summary>
        public NotificationAdressUpdateDto(Guid? queuId = default(Guid?), string notificationAdress = default(string))
        {
            QueuId = queuId;
            NotificationAdress = notificationAdress;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "queuId")]
        public Guid? QueuId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "notificationAdress")]
        public string NotificationAdress { get; set; }

    }
}
