// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Harrison314.PassiveMQ.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PublishResult
    {
        /// <summary>
        /// Initializes a new instance of the PublishResult class.
        /// </summary>
        public PublishResult() { }

        /// <summary>
        /// Initializes a new instance of the PublishResult class.
        /// </summary>
        public PublishResult(IList<PublishPair> cratedMessages = default(IList<PublishPair>))
        {
            CratedMessages = cratedMessages;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cratedMessages")]
        public IList<PublishPair> CratedMessages { get; set; }

    }
}
