CREATE TABLE [dbo].[Message]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [QueuRecordId] UNIQUEIDENTIFIER NOT NULL, 
    [Created] DATETIME2 NOT NULL,
	[Label] NVARCHAR(1024) NULL DEFAULT NULL,
    [Content] NVARCHAR(MAX) NOT NULL, 
    [NextVisible] DATETIME2 NULL DEFAULT NULL, 
    [RetryCount] INT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_Message_QueuRecord] FOREIGN KEY ([QueuRecordId]) REFERENCES [dbo].[QueuRecord]([Id]) ON DELETE CASCADE
)
